# Generated by Django 5.2 on 2025-05-26 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_marketplace', '0002_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('CLOSED', 'Closed'), ('EXPIRED', 'Expired'), ('SUSPENDED', 'Suspended'), ('CANCELLED', 'Cancelled'), ('OPEN', 'Open')], default='Open', max_length=20),
        ),
    ]
