# Generated by Django 5.2 on 2025-05-26 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_marketplace', '0003_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('SUSPENDED', 'Suspended'), ('CLOSED', 'Closed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='Open', max_length=20),
        ),
    ]
