# Generated by Django 5.2 on 2025-05-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_marketplace', '0004_alter_project_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='due_date',
        ),
        migrations.AddField(
            model_name='project',
            name='no_of_days',
            field=models.IntegerField(default=5),
        ),
    ]
