# Generated by Django 5.2 on 2025-05-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_marketplace', '0005_remove_project_due_date_project_no_of_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('SUSPENDED', 'Suspended'), ('CLOSED', 'Closed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='Open', max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=25),
        ),
    ]
