# Generated by Django 5.2 on 2025-05-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_channelgroup_channel_guid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelgroup',
            name='channel_guid',
            field=models.CharField(max_length=50),
        ),
    ]
