# Generated by Django 5.2 on 2025-04-22 03:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='worker',
            name='Ratings',
            field=models.DecimalField(decimal_places=1, default=None, max_digits=2),
        ),
    ]
