# Generated by Django 5.2 on 2025-04-22 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0004_alter_user_email_id_alter_user_phone_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.CharField(max_length=12),
        ),
    ]
