# Generated by Django 5.2 on 2025-04-22 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0005_alter_user_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='Ratings',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
