# Generated by Django 5.2 on 2025-04-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0008_user_profile_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='Ratings',
            new_name='ratings',
        ),
        migrations.AddField(
            model_name='worker',
            name='q1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='q2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='q3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='q4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='q5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='status',
            field=models.IntegerField(choices=[(1, 'ready'), (2, 'on project'), (3, 'unavailable')], default=1),
        ),
    ]
